/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCategoriesRouteImport } from './routes/admin.categories'
import { Route as AdminFaqsRouteImport } from './routes/admin.faqs'
import { Route as AdminIndustriesRouteImport } from './routes/admin.industries'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminKnowledgeRouteImport } from './routes/admin.knowledge'
import { Route as AdminLogsRouteImport } from './routes/admin.logs'
import { Route as AdminMediaRouteImport } from './routes/admin.media'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminSettingsRouteImport } from './routes/admin.settings'
import { Route as AdminSolutionsRouteImport } from './routes/admin.solutions'
import { Route as AdminStatisticsRouteImport } from './routes/admin.statistics'
import { Route as AdminTeamRouteImport } from './routes/admin.team'
import { Route as AdminTestimonialsRouteImport } from './routes/admin.testimonials'
import { Route as AdminLoginRouteImport } from './routes/admin_.login'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriesRoute = AdminCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFaqsRoute = AdminFaqsRouteImport.update({
  id: '/faqs',
  path: '/faqs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIndustriesRoute = AdminIndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminKnowledgeRoute = AdminKnowledgeRouteImport.update({
  id: '/knowledge',
  path: '/knowledge',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMediaRoute = AdminMediaRouteImport.update({
  id: '/media',
  path: '/media',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSolutionsRoute = AdminSolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => AdminRoute,
} as any)
const AdminStatisticsRoute = AdminStatisticsRouteImport.update({
  id: '/statistics',
  path: '/statistics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTeamRoute = AdminTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTestimonialsRoute = AdminTestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin_/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/admin/categories': typeof AdminCategoriesRoute
  '/admin/faqs': typeof AdminFaqsRoute
  '/admin/industries': typeof AdminIndustriesRoute
  '/admin/inquiries': typeof AdminInquiriesRoute
  '/admin/knowledge': typeof AdminKnowledgeRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/media': typeof AdminMediaRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/admin/products': typeof AdminProductsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/solutions': typeof AdminSolutionsRoute
  '/admin/statistics': typeof AdminStatisticsRoute
  '/admin/team': typeof AdminTeamRoute
  '/admin/testimonials': typeof AdminTestimonialsRoute
  '/admin_/login': typeof AdminLoginRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/inquiries'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/solutions'
    | '/admin/statistics'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/login'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/inquiries'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/solutions'
    | '/admin/statistics'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin/login'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/admin/categories'
    | '/admin/faqs'
    | '/admin/industries'
    | '/admin/inquiries'
    | '/admin/knowledge'
    | '/admin/logs'
    | '/admin/media'
    | '/admin/partners'
    | '/admin/products'
    | '/admin/projects'
    | '/admin/settings'
    | '/admin/solutions'
    | '/admin/statistics'
    | '/admin/team'
    | '/admin/testimonials'
    | '/admin_/login'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categories': {
      id: '/admin/categories'
      path: '/categories'
      fullPath: '/admin/categories'
      preLoaderRoute: typeof AdminCategoriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/faqs': {
      id: '/admin/faqs'
      path: '/faqs'
      fullPath: '/admin/faqs'
      preLoaderRoute: typeof AdminFaqsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/industries': {
      id: '/admin/industries'
      path: '/industries'
      fullPath: '/admin/industries'
      preLoaderRoute: typeof AdminIndustriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/knowledge': {
      id: '/admin/knowledge'
      path: '/knowledge'
      fullPath: '/admin/knowledge'
      preLoaderRoute: typeof AdminKnowledgeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/media': {
      id: '/admin/media'
      path: '/media'
      fullPath: '/admin/media'
      preLoaderRoute: typeof AdminMediaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/solutions': {
      id: '/admin/solutions'
      path: '/solutions'
      fullPath: '/admin/solutions'
      preLoaderRoute: typeof AdminSolutionsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/statistics': {
      id: '/admin/statistics'
      path: '/statistics'
      fullPath: '/admin/statistics'
      preLoaderRoute: typeof AdminStatisticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/team': {
      id: '/admin/team'
      path: '/team'
      fullPath: '/admin/team'
      preLoaderRoute: typeof AdminTeamRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/testimonials': {
      id: '/admin/testimonials'
      path: '/testimonials'
      fullPath: '/admin/testimonials'
      preLoaderRoute: typeof AdminTestimonialsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin_/login': {
      id: '/admin_/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriesRoute: typeof AdminCategoriesRoute
  AdminFaqsRoute: typeof AdminFaqsRoute
  AdminIndustriesRoute: typeof AdminIndustriesRoute
  AdminInquiriesRoute: typeof AdminInquiriesRoute
  AdminKnowledgeRoute: typeof AdminKnowledgeRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminMediaRoute: typeof AdminMediaRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  AdminProductsRoute: typeof AdminProductsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminSolutionsRoute: typeof AdminSolutionsRoute
  AdminStatisticsRoute: typeof AdminStatisticsRoute
  AdminTeamRoute: typeof AdminTeamRoute
  AdminTestimonialsRoute: typeof AdminTestimonialsRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriesRoute: AdminCategoriesRoute,
  AdminFaqsRoute: AdminFaqsRoute,
  AdminIndustriesRoute: AdminIndustriesRoute,
  AdminInquiriesRoute: AdminInquiriesRoute,
  AdminKnowledgeRoute: AdminKnowledgeRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminMediaRoute: AdminMediaRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  AdminProductsRoute: AdminProductsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminSolutionsRoute: AdminSolutionsRoute,
  AdminStatisticsRoute: AdminStatisticsRoute,
  AdminTeamRoute: AdminTeamRoute,
  AdminTestimonialsRoute: AdminTestimonialsRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
