INSERT INTO public.product_categories (name, slug, description, image_url, icon, sort_order) VALUES
('IP Phones','ip-phones','CoreIP Vaani and T-series IP phones for desks, reception and enterprise deployments.','/media/IP-Phones.jpg','phone',1),
('Communication','communication','Unified communication servers and cloud communication platforms.','/media/unified_communication-2.jpg','radio',2),
('Networking','networking','Network management and monitoring products.','/media/netword-management.jpg','network',3),
('Security','security','Video management, video analytics and surveillance products.','/media/video-management-system.jpg','shield',4),
('Media Gateways','media-gateways','Gateways that bridge legacy telecom lines into an IP communication core.','/media/media_gateway.jpg','radio',5),
('Servers','servers','Enterprise and industrial grade server platforms.','/media/server.png','server',6),
('Storage','storage','Network attached storage for recordings, archives and enterprise data.','/media/coreip-UNAS.png','database',7),
('Software','software','Enterprise software for call accounting and complaint management.','/media/call_biling.jpg','code',8);

INSERT INTO public.products (name, slug, category_id, short_description, long_description, image_url, features, applications, cta_text, cta_link, seo_title, seo_description, status, sort_order) VALUES
('CoreIP Vaani-101P','coreip-vaani-101p',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'Entry-level CoreIP Vaani IP phone for everyday enterprise desks.','The CoreIP Vaani-101P is part of the CoreIP Vaani IP phone range, designed for enterprise desk deployments on CoreIP unified communication platforms.','/media/vaani-101P.png','{"HD voice","PoE support","Provisioning at scale"}','{"Enterprise desks","Reception","Campus deployments"}','Request a Quote','/contact','CoreIP Vaani-101P IP Phone','Entry-level CoreIP Vaani-101P IP phone for enterprise desk deployments on CoreIP unified communication platforms.','published',1),
('CoreIP Vaani-102P','coreip-vaani-102p',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'CoreIP Vaani IP phone for enterprise desk and reception use.','The CoreIP Vaani-102P belongs to the CoreIP Vaani IP phone family used across enterprise and institutional deployments.','/media/vaani-101P.png','{"HD voice","PoE support","Multi-line support"}','{"Enterprise desks","Reception"}','Request a Quote','/contact','CoreIP Vaani-102P IP Phone','CoreIP Vaani-102P IP phone for enterprise desk and reception deployments.','published',2),
('CoreIP Vaani-102G','coreip-vaani-102g',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'Gigabit variant of the CoreIP Vaani IP phone range.','The CoreIP Vaani-102G is the gigabit variant in the CoreIP Vaani IP phone range for enterprise networks.','/media/vaani-101P.png','{"HD voice","Gigabit ports","PoE support"}','{"Enterprise desks","Gigabit networks"}','Request a Quote','/contact','CoreIP Vaani-102G IP Phone','CoreIP Vaani-102G gigabit IP phone for enterprise networks.','published',3),
('CoreIP T23G','coreip-t23g',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'CoreIP T-series IP phone for high-volume desk deployments.','The CoreIP T23G is part of the CoreIP T-series IP phone range offered for enterprise deployments.','/media/IP-Phones.jpg','{"HD voice","Gigabit ports","Multi-line support"}','{"Enterprise desks","Call centres"}','Request a Quote','/contact','CoreIP T23G IP Phone','CoreIP T23G IP phone for enterprise desk deployments.','published',4),
('CoreIP T43U','coreip-t43u',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'CoreIP T-series IP phone with USB support for professional users.','The CoreIP T43U is part of the CoreIP T-series IP phone range for professional enterprise users.','/media/IP-Phones.jpg','{"HD voice","USB support","Gigabit ports"}','{"Managers","Professional users"}','Request a Quote','/contact','CoreIP T43U IP Phone','CoreIP T43U IP phone with USB support for professional enterprise users.','published',5),
('CoreIP T46U','coreip-t46u',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'CoreIP T-series executive IP phone with large display.','The CoreIP T46U is an executive model in the CoreIP T-series IP phone range.','/media/IP-Phones.jpg','{"HD voice","Large display","USB support"}','{"Executives","Management desks"}','Request a Quote','/contact','CoreIP T46U IP Phone','CoreIP T46U executive IP phone with large display.','published',6),
('CoreIP T-58W','coreip-t-58w',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'Smart CoreIP IP phone with touch display for executive desks.','The CoreIP T-58W is a smart IP phone in the CoreIP range, intended for executive and collaboration-focused desks.','/media/IP-Phones.jpg','{"Touch display","HD voice","Wireless connectivity"}','{"Executive desks","Collaboration rooms"}','Request a Quote','/contact','CoreIP T-58W Smart IP Phone','CoreIP T-58W smart IP phone with touch display for executive desks.','published',7),
('CoreIP T-58W PRO','coreip-t-58w-pro',(SELECT id FROM public.product_categories WHERE slug='ip-phones'),'Top-of-range smart CoreIP IP phone for executive collaboration.','The CoreIP T-58W PRO is the top-of-range smart IP phone in the CoreIP portfolio for executive collaboration.','/media/IP-Phones.jpg','{"Touch display","HD voice","Video capable","Wireless connectivity"}','{"Executive desks","Video collaboration"}','Request a Quote','/contact','CoreIP T-58W PRO Smart IP Phone','CoreIP T-58W PRO smart IP phone for executive collaboration.','published',8),
('Unified Communication Server','unified-communication-server',(SELECT id FROM public.product_categories WHERE slug='communication'),'The core of enterprise voice, video and messaging on a single platform.','CoreIP Unified Communication Server delivers IPPBX telephony, conferencing and collaboration on a single platform and has been deployed at scale across government and enterprise organisations.','/media/unified_communication-2.jpg','{"IPPBX telephony","Conferencing","Scales to 5000+ lines"}','{"Government","Enterprise","Campus"}','Talk to an Expert','/contact','CoreIP Unified Communication Server','CoreIP Unified Communication Server for enterprise voice, video and messaging, scaling to 5000+ lines.','published',9),
('UCX on Cloud','ucx-on-cloud',(SELECT id FROM public.product_categories WHERE slug='communication'),'Hosted unified communication for distributed and multi-site organisations.','CoreIP UCX on Cloud delivers hosted unified communication for multi-site organisations, with site-to-site dialling and elastic capacity.','/media/ucx_on_cloud.jpg','{"Cloud delivered","Site-to-site dialling","Elastic capacity"}','{"Multi-site enterprises","Distributed teams"}','Request a Demo','/contact','CoreIP UCX on Cloud','Hosted CoreIP UCX unified communication for distributed and multi-site organisations.','published',10),
('CoreIP NMS','coreip-nms',(SELECT id FROM public.product_categories WHERE slug='networking'),'Network management with complete visibility of devices, links and performance.','CoreIP NMS is a network management and monitoring product providing visibility of network devices, links and performance from a central console.','/media/netword-management.jpg','{"Topology view","Performance graphs","Alerting","Device management"}','{"Enterprise networks","Campus networks","Data centres"}','Explore NMS','/contact','CoreIP NMS — Network Management Software','CoreIP NMS network management software with topology view, performance monitoring and alerting.','published',11),
('CoreIP UVMS','coreip-uvms',(SELECT id FROM public.product_categories WHERE slug='security'),'Unified video management for centralised surveillance operations.','CoreIP UVMS (Unified Video Management Server) centralises multi-site video surveillance, recording and monitoring in a single console.','/media/video-management-system.jpg','{"Multi-site video","Recording","Central console"}','{"Surveillance operations","Multi-site premises"}','Talk to an Expert','/contact','CoreIP UVMS — Unified Video Management Server','CoreIP UVMS unified video management server for centralised, multi-site surveillance operations.','published',12),
('VMS / VA / FRS','vms-va-frs',(SELECT id FROM public.product_categories WHERE slug='security'),'Video management, video analytics and face recognition on one platform.','CoreIP VMS / VA / FRS combines video management, video analytics and face recognition capabilities for security-driven deployments.','/media/NVS_coreip.jpg','{"Video management","Video analytics","Face recognition"}','{"Security operations","Access control","Public safety"}','Talk to an Expert','/contact','CoreIP VMS / VA / FRS','CoreIP VMS, video analytics and face recognition platform for security-driven deployments.','published',13),
('CoreIP UMGW','coreip-umgw',(SELECT id FROM public.product_categories WHERE slug='media-gateways'),'CoreIP unified media gateway bridging telecom lines into IP.','CoreIP UMGW is a unified media gateway that connects analog and digital telecom lines into an IP communication core.','/media/8FXS.png','{"Analog & digital ports","Trunk failover","SIP interworking"}','{"Legacy telecom migration","Trunk integration"}','Request a Quote','/contact','CoreIP UMGW Unified Media Gateway','CoreIP UMGW unified media gateway connecting analog and digital telecom lines into an IP core.','published',14),
('Media Gateways','media-gateways-product',(SELECT id FROM public.product_categories WHERE slug='media-gateways'),'Bridge PRI, FXO and FXS telecom lines into an IP communication core.','CoreIP media gateways bridge PRI, FXO and FXS telecom lines into an IP communication core with trunk failover and SIP interworking.','/media/media_gateway.jpg','{"PRI / FXO / FXS ports","Trunk failover","SIP interworking"}','{"Telecom integration","Hybrid communication"}','Request a Quote','/contact','CoreIP Media Gateways','CoreIP media gateways for PRI, FXO and FXS telecom integration with IP communication cores.','published',15),
('CoreIP UCS-1000RPS','coreip-ucs-1000rps',(SELECT id FROM public.product_categories WHERE slug='servers'),'CoreIP unified communication server hardware with redundant power.','CoreIP UCS-1000RPS is a server platform configured for CoreIP unified communication workloads with redundant power supply.','/media/server.png','{"Redundant power supply","Rack form factor","Communication workload sizing"}','{"Unified communication","On-premise deployments"}','Request a Quote','/contact','CoreIP UCS-1000RPS Server','CoreIP UCS-1000RPS unified communication server platform with redundant power supply.','published',16),
('Industrial Grade COTS Servers','industrial-grade-cots-servers',(SELECT id FROM public.product_categories WHERE slug='servers'),'Commercial off-the-shelf server platforms for demanding environments.','CoreIP industrial grade COTS servers are commercial off-the-shelf server platforms configured for communication, video and application workloads.','/media/server-1.png','{"Rack form factors","Workload sizing","On-site support"}','{"Communication workloads","Video workloads","Application hosting"}','Request a Quote','/contact','Industrial Grade COTS Servers — CoreIP','CoreIP industrial grade COTS servers for communication, video and application workloads.','published',17),
('CoreIP UNAS','coreip-unas',(SELECT id FROM public.product_categories WHERE slug='storage'),'Unified network attached storage for recordings, archives and data.','CoreIP UNAS is unified network attached storage for video recordings, archives and enterprise data, with expandable capacity and RAID protection.','/media/coreip-UNAS.png','{"Expandable capacity","RAID protection","Network shares"}','{"Video archives","Enterprise data","Backup"}','Request a Quote','/contact','CoreIP UNAS — Unified Network Attached Storage','CoreIP UNAS unified network attached storage with expandable capacity and RAID protection.','published',18),
('Call Billing Software','call-billing-software',(SELECT id FROM public.product_categories WHERE slug='software'),'Accurate call accounting and cost control across extensions and trunks.','CoreIP Call Billing Software provides call detail records, department-wise billing and usage reporting for accurate call accounting and cost control.','/media/call_biling.jpg','{"Call detail records","Department-wise billing","Usage reports"}','{"Cost control","Telecom accounting"}','Request a Demo','/contact','CoreIP Call Billing Software','CoreIP call billing software with call detail records, department-wise billing and usage reports.','published',19),
('Complaint Management System','complaint-management-system',(SELECT id FROM public.product_categories WHERE slug='software'),'Structured complaint logging, assignment and closure for service teams.','CoreIP Complaint Management System provides structured complaint logging, assignment, escalation and closure for service-driven teams.','/media/Complaint-management-system.jpg','{"Ticket lifecycle","Escalation flow","ISO-aligned records"}','{"Service desks","Support teams","Facility management"}','Request a Demo','/contact','CoreIP Complaint Management System','CoreIP complaint management system with ticket lifecycle, escalation flow and ISO-aligned records.','published',20);

INSERT INTO public.services (name, slug, category, icon, short_description, long_description, hero_image_url, features, benefits, cta_text, cta_link, seo_title, seo_description, status, sort_order, featured) VALUES
('Unified Communication','unified-communication','Communication','phone','IPPBX, VoIP, video conferencing and collaboration on CoreIP''s UCX platform.','CoreIP delivers unified communication across IPPBX, VoIP, video conferencing and collaboration — on premise or on cloud — built on the CoreIP UCX platform.','/media/unified_communication-2.jpg','{"IPPBX / VoIP","Video conferencing","UCX on Cloud"}','{"Single communication platform","Scales to thousands of lines","On premise or cloud"}','Talk to an Expert','/contact','Unified Communication Solutions — CoreIP','CoreIP unified communication solutions: IPPBX, VoIP, video conferencing and collaboration on premise or on cloud.','published',1,true),
('Security Solutions','security-solutions','Security','shield','Surveillance, access and video management deployments.','CoreIP security solutions cover surveillance, access and video management deployments that protect people, premises and information.','/media/video-management-system.jpg','{"Video management (UVMS)","Access & surveillance","Helpline platforms"}','{"Centralised monitoring","Multi-site coverage","Mission-critical reliability"}','Talk to an Expert','/contact','Security Solutions — CoreIP','CoreIP security solutions covering surveillance, access control and unified video management.','published',2,true),
('Networking Solutions','networking-solutions','Networking','network','Structured, resilient enterprise networks with centralised monitoring.','CoreIP designs structured, resilient enterprise networks with centralised monitoring and device management through CoreIP NMS.','/media/netword-management.jpg','{"LAN / WAN design","Network monitoring","Device management"}','{"Resilient connectivity","Central visibility","Faster fault resolution"}','Talk to an Expert','/contact','Networking Solutions — CoreIP','CoreIP networking solutions: LAN/WAN design, network monitoring and device management.','published',3,true),
('Telecom Solutions','telecom-solutions','Telecom','radio','Media gateways, trunking and call management for hybrid telecom.','CoreIP telecom solutions connect legacy telecom with modern IP infrastructure using media gateways, trunk integration and call management.','/media/media_gateway.jpg','{"Media gateways","Call billing","Trunk integration"}','{"Protects existing investment","Hybrid migration path","Cost visibility"}','Talk to an Expert','/contact','Telecom Solutions — CoreIP','CoreIP telecom solutions with media gateways, trunk integration and call billing.','published',4,true),
('Hosting Solutions','hosting-solutions','Hosting','cloud','Servers, storage and hosted communication infrastructure.','CoreIP hosting solutions provide servers, storage and hosted communication infrastructure sized for enterprise and government workloads.','/media/server.png','{"COTS servers","UNAS storage","Hosted UCX"}','{"Right-sized capacity","Expandable storage","Managed infrastructure"}','Talk to an Expert','/contact','Hosting Solutions — CoreIP','CoreIP hosting solutions: COTS servers, UNAS storage and hosted UCX communication.','published',5,true),
('Video Conferencing','video-conferencing','Communication','video','Meeting-room and desktop video collaboration for distributed teams.','CoreIP video conferencing brings meeting-room and desktop video collaboration to distributed organisations as part of the unified communication platform.','/media/ucx_on_cloud.jpg','{"Room and desktop video","Multi-party conferencing","Cloud or on premise"}','{"Faster decisions","Lower travel cost","Consistent experience"}','Request a Demo','/contact','Video Conferencing Solutions — CoreIP','CoreIP video conferencing for meeting rooms and desktops, on cloud or on premise.','published',6,false),
('Network Management','network-management','Networking','activity','Centralised monitoring of devices, links and performance.','CoreIP network management, delivered through CoreIP NMS, gives centralised visibility of devices, links and performance across the enterprise network.','/media/nms-dashboard.jpg','{"Topology view","Performance monitoring","Alerting"}','{"Proactive fault detection","Single pane of glass","Better uptime"}','Explore NMS','/contact','Network Management — CoreIP','Centralised network management and monitoring with CoreIP NMS.','published',7,false),
('Enterprise Hardware','enterprise-hardware','Hardware','server','Servers, storage and communication hardware for enterprise workloads.','CoreIP supplies and supports enterprise hardware — servers, storage and communication appliances — configured for the workloads they run.','/media/server-1.png','{"COTS and industrial servers","UNAS storage","Media gateways"}','{"Workload-matched sizing","Warranty support","On-site service"}','Request a Quote','/contact','Enterprise Hardware — CoreIP','CoreIP enterprise hardware: servers, storage and communication appliances.','published',8,false);

INSERT INTO public.industries (name, slug, description, hero_image_url, icon, status, sort_order, seo_title, seo_description) VALUES
('Manufacturing','manufacturing','Plant-wide communication, networking and surveillance for manufacturing operations.','/media/ind-manufacturing.jpg','factory','published',1,'Manufacturing Solutions — CoreIP','CoreIP communication, networking and surveillance solutions for manufacturing operations.'),
('Warehouse','warehouse','Connected warehouse communication, coverage and monitoring.','/media/ind-warehouse.jpg','package','published',2,'Warehouse Solutions — CoreIP','CoreIP communication, network coverage and monitoring solutions for warehouses.'),
('Healthcare','healthcare','Reliable communication and surveillance for hospitals and healthcare campuses.','/media/ind-healthcare.jpg','heart-pulse','published',3,'Healthcare Solutions — CoreIP','CoreIP communication and surveillance solutions for hospitals and healthcare campuses.'),
('Retail','retail','Multi-store communication, networking and video for retail chains.','/media/ind-retail.jpg','store','published',4,'Retail Solutions — CoreIP','CoreIP multi-store communication, networking and video solutions for retail.'),
('Hospitality','hospitality','Guest-facing communication and property-wide connectivity.','/media/ind-hospitality.jpg','concierge-bell','published',5,'Hospitality Solutions — CoreIP','CoreIP guest communication and property-wide connectivity for hospitality.'),
('Education','education','Campus-wide voice, collaboration and safety infrastructure.','/media/ind-education.jpg','graduation-cap','published',6,'Education & Campus Solutions — CoreIP','CoreIP campus-wide voice, collaboration and safety infrastructure for education.');

INSERT INTO public.projects (title, slug, customer, solution, description, highlights, industry_id, cover_image_url, status, sort_order, seo_title, seo_description) VALUES
('Railway Board Unified Communication','railway-board-unified-communication','Railway Board','Unified Communication','5000-line unified communication deployment for Railway Board.','{"5000 lines","Unified communication platform"}',NULL,'/media/unified_communication-2.jpg','published',1,'Railway Board Unified Communication — CoreIP','CoreIP 5000-line unified communication deployment for Railway Board.'),
('NBCC Communication Infrastructure','nbcc-communication-infrastructure','NBCC','Unified Communication','5000-line communication infrastructure rollout for NBCC.','{"5000 lines","Communication infrastructure rollout"}',NULL,'/media/unified_communication-2.jpg','published',2,'NBCC Communication Infrastructure — CoreIP','CoreIP 5000-line communication infrastructure rollout for NBCC.'),
('IIM Campus Communication Platform','iim-campus-communication-platform','IIM','Unified Communication','2000-line campus communication platform for IIM.','{"2000 lines","Campus-wide platform"}',(SELECT id FROM public.industries WHERE slug='education'),'/media/ind-education.jpg','published',3,'IIM Campus Communication Platform — CoreIP','CoreIP 2000-line campus communication platform deployed for IIM.'),
('NTPC Enterprise Voice Deployment','ntpc-enterprise-voice-deployment','NTPC','Unified Communication','1000-line enterprise voice deployment for NTPC.','{"1000 lines","Enterprise voice"}',NULL,'/media/unified_communication-2.jpg','published',4,'NTPC Enterprise Voice Deployment — CoreIP','CoreIP 1000-line enterprise voice deployment for NTPC.'),
('182 Security Helpline','182-security-helpline','182 Security Helpline','Helpline Communication','Mission-critical public helpline communication infrastructure.','{"Mission-critical helpline","Public safety"}',NULL,'/media/NVS_coreip.jpg','published',5,'182 Security Helpline — CoreIP','CoreIP mission-critical public helpline communication infrastructure for the 182 Security Helpline.'),
('Voter Helpline Platform','voter-helpline-platform','Voter Helpline','Helpline Communication','High-volume citizen helpline communication platform.','{"High-volume citizen helpline"}',NULL,'/media/unified_communication-2.jpg','published',6,'Voter Helpline Platform — CoreIP','CoreIP high-volume citizen helpline communication platform.'),
('Central Secretariat Communication','central-secretariat-communication','Central Secretariat','Unified Communication','Government communication infrastructure deployment.','{"Government infrastructure"}',NULL,'/media/unified_communication-2.jpg','published',7,'Central Secretariat Communication — CoreIP','CoreIP government communication infrastructure for the Central Secretariat.'),
('Subharti University Campus Communication','subharti-university-campus-communication','Subharti University','Campus Communication','Campus-wide voice and collaboration deployment.','{"Campus-wide voice","Collaboration"}',(SELECT id FROM public.industries WHERE slug='education'),'/media/ind-education.jpg','published',8,'Subharti University Campus Communication — CoreIP','CoreIP campus-wide voice and collaboration deployment for Subharti University.'),
('TUV Enterprise Communication','tuv-enterprise-communication','TUV','Enterprise Communication','Enterprise communication implementation for TUV.','{"Enterprise communication"}',NULL,'/media/unified_communication-2.jpg','published',9,'TUV Enterprise Communication — CoreIP','CoreIP enterprise communication implementation for TUV.');

INSERT INTO public.website_statistics (label, value, suffix, icon, sort_order) VALUES
('Projects Completed',20,'+','briefcase',1),
('Team Members',50,'+','users',2),
('Happy Clients',200,'+','heart',3),
('Years of Service',6,'+','calendar',4);

INSERT INTO public.website_settings (key, group_name, value) VALUES
('contact_info','contact','{"primary_phone":"+91-120-6618000","sales_phone":"+91-120-6618005","support_phone":"+91-120-6618000","email":"info@coreip.co.in","sales_email":"info@coreip.co.in","support_email":"info@coreip.co.in","address":"C-421, The iThum, A-40, Sector-62, Noida 201309, Uttar Pradesh, India","maps_url":"https://maps.google.com/?q=The+iThum+A-40+Sector+62+Noida","whatsapp":"+911206618000","business_hours":"Monday to Saturday, 9:30 AM to 6:30 PM IST"}'),
('social_links','contact','{"linkedin":"","twitter":"","facebook":"","youtube":""}'),
('seo_defaults','seo','{"site_name":"CoreIP","default_title":"CoreIP — Unified Communication, Networking & Security Solutions","default_description":"CoreIP delivers enterprise unified communication, IPPBX/VoIP, networking, network management, security and hosting solutions across India.","og_image":"/media/hero-network.jpg"}'),
('homepage','homepage','{"hero_eyebrow":"Enterprise Technology Solutions","hero_headline":"Smarter Communication. Stronger Infrastructure.","hero_description":"CoreIP designs, deploys and supports unified communication, networking, security and hosting infrastructure for enterprises, institutions and government organisations.","hero_image":"/media/hero-network.jpg","hero_primary_cta_label":"Talk to an Expert","hero_primary_cta_link":"/contact","hero_secondary_cta_label":"Explore Solutions","hero_secondary_cta_link":"/solutions","show_statistics":true,"show_partners":true,"show_testimonials":false}'),
('cta_labels','cta','{"talk_to_expert":"Talk to an Expert","request_quote":"Request a Quote","contact_sales":"Contact Sales","request_demo":"Request a Demo","download_brochure":"Download Brochure","explore_product":"Explore Product"}'),
('footer','footer','{"tagline":"CoreIP helps organisations build secure, connected and intelligent communication infrastructure.","blog_url":"https://www.coreip.co.in/blog/","privacy_url":"https://www.coreip.co.in/privacy-policy/","terms_url":"https://www.coreip.co.in/terms-condition/"}'),
('chatbot','chatbot','{"enabled":true,"title":"CoreIP Assistant","greeting":"Hi! Ask me about CoreIP products, solutions, industries or how to reach the team.","fallback":"I could not find that information in the CoreIP knowledge base. Please contact the CoreIP team for confirmation.","suggested_questions":["What products does CoreIP offer?","Tell me about IP Phones","What is CoreIP NMS?","Tell me about VMS / VA / FRS","How can I contact CoreIP?"],"use_ai":true}'),
('navigation','navigation','{"show_products":true,"show_solutions":true,"show_industries":true,"show_projects":true,"show_team":true,"max_products_in_menu":8}');

INSERT INTO public.partners (name, sort_order) VALUES
('Matrix',1);

INSERT INTO public.faqs (question, answer, category, sort_order) VALUES
('What does CoreIP do?','CoreIP designs, deploys and supports unified communication, networking, security, telecom and hosting infrastructure for enterprises, institutions and government organisations.','Company',1),
('Which IP phones does CoreIP provide?','CoreIP provides the Vaani range (Vaani-101P, Vaani-102P, Vaani-102G) and the T-series (T23G, T43U, T46U, T-58W and T-58W PRO).','Products',2),
('What is CoreIP NMS?','CoreIP NMS is network management software that gives centralised visibility of network devices, links and performance, with topology views, performance graphs and alerting.','Products',3),
('What is UCX?','UCX is CoreIP''s unified communication platform, available on premise through the Unified Communication Server or hosted as UCX on Cloud.','Products',4),
('What is VMS / VA / FRS?','VMS / VA / FRS is CoreIP''s combined video management, video analytics and face recognition offering for security-driven deployments.','Products',5),
('Which servers does CoreIP provide?','CoreIP provides the UCS-1000RPS server platform and industrial grade COTS servers configured for communication, video and application workloads.','Products',6),
('Which industries does CoreIP serve?','CoreIP serves manufacturing, warehousing, healthcare, retail, hospitality and education, alongside government and institutional customers.','Company',7),
('How can I request a demo or quote?','Use the Request a Quote form on any product or solution page, or contact the CoreIP team by phone or email from the Contact page.','Support',8);

INSERT INTO public.knowledge_articles (title, category, content, keywords, link_url, link_label) VALUES
('About CoreIP','Company','CoreIP is an enterprise technology company that designs, deploys and supports unified communication, networking, security, telecom and hosting infrastructure. CoreIP has delivered large-scale communication deployments for government and enterprise organisations including Railway Board, NBCC, NTPC and IIM.','{"about","company","coreip","who"}','/about','About CoreIP'),
('Contacting CoreIP','Contact','You can reach CoreIP at +91-120-6618000 or +91-120-6618005, by email at info@coreip.co.in, or at C-421, The iThum, A-40, Sector-62, Noida 201309, Uttar Pradesh, India. You can also submit the contact form on the website.','{"contact","phone","email","address","reach","support"}','/contact','Contact CoreIP'),
('CoreIP IP Phones','Products','CoreIP offers the Vaani IP phone range (Vaani-101P, Vaani-102P and the gigabit Vaani-102G) and the T-series (T23G, T43U, T46U, T-58W and T-58W PRO) for desks, reception and executive use, with HD voice, PoE support and provisioning at scale.','{"ip phone","phones","vaani","t23g","t43u","t46u","t58w","desk phone"}','/products/ip-phones','Explore IP Phones'),
('CoreIP NMS','Products','CoreIP NMS is network management software providing complete visibility of network devices, links and performance, including topology views, performance graphs, alerting and device management.','{"nms","network management","monitoring","topology"}','/products/networking/coreip-nms','Explore CoreIP NMS'),
('CoreIP UVMS','Products','CoreIP UVMS (Unified Video Management Server) centralises multi-site video surveillance, recording and monitoring in a single console.','{"uvms","video management","surveillance","cctv"}','/products/security/coreip-uvms','Explore CoreIP UVMS'),
('VMS / VA / FRS','Products','CoreIP VMS / VA / FRS combines video management, video analytics and face recognition capabilities for security operations, access control and public safety deployments.','{"vms","va","frs","video analytics","face recognition"}','/products/security/vms-va-frs','Explore VMS / VA / FRS'),
('Unified Communication Server and UCX','Products','The CoreIP Unified Communication Server delivers IPPBX telephony, conferencing and collaboration on one platform and scales beyond 5000 lines. UCX on Cloud provides the same unified communication hosted for multi-site organisations with site-to-site dialling and elastic capacity.','{"ucx","unified communication","ippbx","voip","cloud","server"}','/products/communication/unified-communication-server','Explore Unified Communication'),
('CoreIP Servers','Products','CoreIP provides the UCS-1000RPS unified communication server platform with redundant power supply, and industrial grade COTS servers configured for communication, video and application workloads.','{"server","ucs-1000rps","cots","hardware","rack"}','/products/servers','Explore Servers'),
('CoreIP UNAS Storage','Products','CoreIP UNAS is unified network attached storage for video recordings, archives and enterprise data, offering expandable capacity, RAID protection and network shares.','{"unas","storage","nas","backup","archive"}','/products/storage/coreip-unas','Explore CoreIP UNAS'),
('CoreIP Media Gateways and UMGW','Products','CoreIP UMGW and the CoreIP media gateway range bridge PRI, FXO and FXS telecom lines into an IP communication core, with trunk failover and SIP interworking.','{"media gateway","umgw","pri","fxo","fxs","trunk","telecom"}','/products/media-gateways','Explore Media Gateways'),
('Call Billing Software','Products','CoreIP Call Billing Software provides call detail records, department-wise billing and usage reports for accurate call accounting and cost control across extensions and trunks.','{"call billing","call accounting","cdr","billing software"}','/products/software/call-billing-software','Explore Call Billing'),
('Complaint Management System','Products','The CoreIP Complaint Management System provides structured complaint logging, assignment, escalation and closure with ISO-aligned records for service-driven teams.','{"complaint management","ticket","helpdesk","cms"}','/products/software/complaint-management-system','Explore Complaint Management'),
('CoreIP Solutions Overview','Solutions','CoreIP delivers unified communication, security, networking, telecom and hosting solutions, along with video conferencing, network management and enterprise hardware services.','{"solutions","services","unified communication","networking","security","telecom","hosting"}','/solutions','Explore Solutions'),
('Industries CoreIP Serves','Industries','CoreIP serves manufacturing, warehousing, healthcare, retail, hospitality and education customers, in addition to government and institutional organisations.','{"industries","manufacturing","warehouse","healthcare","retail","hospitality","education","sectors"}','/industries','Explore Industries'),
('CoreIP Deployments','Projects','CoreIP has delivered 5000-line unified communication deployments for Railway Board and NBCC, a 2000-line campus platform for IIM, a 1000-line enterprise voice deployment for NTPC, plus the 182 Security Helpline, Voter Helpline, Central Secretariat, Subharti University and TUV.','{"projects","deployments","customers","clients","railway","nbcc","ntpc","iim","helpline"}','/projects','View Deployments'),
('Requesting a Demo or Quote','Support','You can request a demo or quote from any CoreIP product or solution page using the Request a Quote form, which captures the product or service you were viewing, or by contacting the CoreIP team directly.','{"demo","quote","pricing enquiry","request","sales"}','/contact','Request a Quote');